# syntax = docker/dockerfile:experimental
FROM python:3.8-buster

RUN apt-get update
RUN apt install -y git
RUN apt install -y libgit2-dev=1.1.0
RUN apt list --installed
RUN mkdir -p /usr/src/app

#COPY . /usr/src/app
WORKDIR /usr/src/app
COPY requirements.txt /usr/src/app/
COPY init.sh /usr/src/app/
RUN pip3 install --no-cache-dir -r requirements.txt

ENTRYPOINT ["sh","init.sh"]